language: cpp

compiler: clang

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/067200a7aea256a9ce83
    on_success: change
    on_failure: always
    on_start: always

script:
  - make
  - make test

os: osx
