language: cpp

compiler:
  - clang
  - gcc

before_install:
  - echo $LANG
  - echo $LC_ALL
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get update && sudo apt-get install -y llvm-3.4 llvm-3.4-dev; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then brew update && brew install llvm35 && brew link --force llvm35; fi

notifications:
  email: false
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/067200a7aea256a9ce83
    on_success: change
    on_failure: always
    on_start: always

script:
  - $CXX --version
  - cmake .
  - make
  - make test

os: osx
